[package]
name = "protector_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
darklua = "0.14.1"
libc = "0.2.167"

[lib]
name = "protector_lib"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.27.0"
